[versions]
agp = "8.13.2"
#agp = "9.0.0"          // CommonExtension doesn't work with this upgrage for now
#kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.1"
composeBom = "2026.01.01"
appcompat = "1.7.1"
material = "1.13.0"
androidxMacroBenchmark = "1.5.0-alpha01"

# Build tools
#agp = "8.11.1"
#composeBom = "2025.07.00"
#kotlin = "2.3.0"
kotlin = "2.3.10"
ksp = "2.2.0-2.0.2"
google-services = "4.4.3"

androidDesugarJdkLibs = "2.1.5"
androidTools = "31.12.0"

# Compose
compose-hot-reload = "1.0.0-beta04"
compose-multiplatform = "1.9.0-beta01"
# Maintain compose multiplatform version aligned with navigation, cache error could happen
compose-lifecycle = "2.9.1"
navigation-compose = "2.9.0-beta04"
jetbrains-core-bundle = "1.0.1"
material-icons = "1.7.3"

# AndroidX
androidx-activity = "1.10.1"
androidx-core = "1.16.0"
androidx-lifecycle = "2.9.0"
androidx-test-ext = "1.2.1"
androidx-runner = "1.6.2"
androidx-test-core = "1.7.0"
appcompatVersion = "1.7.1"
core-splashscreen = "1.0.1"

# Kotlinx
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
kotlinx-datetime = "0.7.1"

# Third party
koin = "4.1.0"
ktor = "3.2.3"
room = "2.7.2"
sqlite = "2.5.2"
datastore = "1.1.7"
firebase-bom = "34.0.0"
adaptive = "1.2.0-alpha04"
compose-jetbrains = "1.8.2"
jetbrains-savedstate = "1.3.1"
coil = "3.3.0"
coil-network = "3.3.0"
moko = "0.19.1"
buildkonfig = "0.17.1"
kermit = "2.0.6"

projectApplicationId = "learn.plcoding.mychirp"
projectVersionName = "1.0"
projectMinSdkVersion = "26"
projectTargetSdkVersion = "36"
projectCompileSdkVersion = "36"
projectVersionCode = "1"

# Desktop Version
desktopPackageName = "MyChirp"
desktopPackageVersion = "1.0.0"
runner = "1.7.0"
truth = "1.4.5"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling  = { group = "androidx.compose.ui", name = "ui-tooling" }

androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Kotlin
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Logging
android-desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
#jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref="compose-jetbrains"}

# Testing
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

# Material 3
#jetbrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref="compose-jetbrains"}
#jetbrains-compose-material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material-icons"}

jetbrains-lifecycle-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose-lifecycle" }

ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref="compose-jetbrains"}


android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
#compose-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-multiplatform" }
androidx-room-gradle-plugin = { module = "androidx.room:room-gradle-plugin", version.ref = "room" }

buildkonfig-gradlePlugin = { group = "com.codingfeline.buildkonfig", name = "buildkonfig-gradle-plugin", version.ref = "buildkonfig" }
buildkonfig-compiler = { group = "com.codingfeline.buildkonfig", name = "buildkonfig-compiler", version.ref = "buildkonfig" }

[plugins]

baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidxMacroBenchmark"}
# Android
#android-libarry to generate the library output, not executables
android-library = { id = "com.android.library", version.ref = "agp" }       # confilicting with 'com.android.application'
android-application = { id = "com.android.application", version.ref = "agp" }
#android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

# Kotlin
#kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

#Convention-plugins
convention-android-application = { id = "create.develop.convention.android.application", version = "unspecified" }  # being referred in below convention plugin
convention-android-application-compose = { id = "create.develop.convention.android.application.compose", version = "unspecified" }

convention-android-library = { id = "create.develop.convention.android.library", version = "unspecified" }


convention-cmp-library = { id = "create.develop.convention.cmp.library", version = "unspecified" }

convention-kmp-library = { id = "create.develop.convention.kmp.library", version = "unspecified" }

convention-cmp-feature = { id = "create.develop.convention.cmp.feature", version = "unspecified" }
#convention-room = { id = "create.develop.convention.room", version = "unspecified" }
#convention-buildkonfig = { id = "create.develop.convention.buildkonfig", version = "unspecified" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

#Compose
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }

#kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
#kotlin---> same as above plugin: 'kotlin-compose'
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

